### ISSUE TITLE
plzip fatal error dependency

### ISSUE THREAD

**Issue by stsmall** [oicr-ibc/cssscl#1]
Hi,
I know that plzip is not your program but it is a dependency. I have all dependencies installed including lzlib-1.8 and also tried lzlib-1.5. lzip runs without error, but plzip will not compile without fatal error. I searched online and could find no mention of this error. I do not have root priveleges so can not do apt-get, I configured everything with the --prefix=$HOME.

gcc 4.4.7 also tried gcc 5.2.0
linux with tsch or zsh

The error is in not finding lzlib.h. I put it in the path it is also in /include. I have no idea why it isnt working. 

Any advice?

error with gcc 5.2.0:
g++  -Wall -W -O2 -c -o arg_parser.o arg_parser.cc
g++  -Wall -W -O2 -c -o file_index.o file_index.cc
g++  -Wall -W -O2 -c -o compress.o compress.cc
compress.cc:34:19: fatal error: lzlib.h: No such file or directory
compilation terminated.
make: **\* [compress.o] Error 1

error with gcc 4.4.7:
g++  -Wall -W -O2 -c -o arg_parser.o arg_parser.cc
g++  -Wall -W -O2 -c -o file_index.o file_index.cc
g++  -Wall -W -O2 -c -o compress.o compress.cc
compress.cc:34:19: error: lzlib.h: No such file or directory
compress.cc: In function ‘void_<unnamed>::cworker(void_)’:
compress.cc:378: error: ‘LZ_min_dictionary_size’ was not declared in this scope
compress.cc:380: error: ‘LZ_Encoder’ was not declared in this scope
compress.cc:380: error: expected primary-expression before ‘const’
compress.cc:380: error: expected ‘;’ before ‘const’
compress.cc:382: error: ‘encoder’ was not declared in this scope
compress.cc:382: error: ‘LZ_compress_errno’ was not declared in this scope
compress.cc:382: error: ‘LZ_ok’ was not declared in this scope
compress.cc:384: error: ‘LZ_mem_error’ was not declared in this scope
compress.cc:395: error: ‘encoder’ was not declared in this scope
compress.cc:395: error: ‘LZ_compress_write_size’ was not declared in this scope
compress.cc:400: error: ‘LZ_compress_write’ was not declared in this scope
compress.cc:405: error: ‘LZ_compress_finish’ was not declared in this scope
compress.cc:407: error: ‘encoder’ was not declared in this scope
compress.cc:408: error: ‘LZ_compress_read’ was not declared in this scope
compress.cc:414: error: ‘LZ_compress_errno’ was not declared in this scope
compress.cc:414: error: ‘LZ_strerror’ was not declared in this scope
compress.cc:420: error: ‘LZ_compress_finished’ was not declared in this scope
compress.cc:423: error: ‘encoder’ was not declared in this scope
compress.cc:423: error: ‘LZ_compress_close’ was not declared in this scope
compress.cc:378: warning: unused variable ‘dict_size’
compress.cc:368: warning: unused variable ‘match_len_limit’
make: **\* [compress.o] Error 1

**Comment by iborozan** [comment]
Hi, 

Not really sure why lzlib.h can not be found on your system.

If you do not have root privileges maybe you could try installing it on a VM with root privileges? 

On Debian GNU/Linux 8.1 or Ubuntu 12.04 LTS make sure to have:

$ sudo apt-get update
$ sudo apt-get install build-essential g++ libxml2-dev libxslt-dev gfortran libopenblas-dev liblapack-dev

Then try (as described in https://github.com/oicr-ibc/cssscl/blob/master/README.rst)

Step 1. Donwload lzlib-1.5.tar.gz

$ wget --no-check-certificate http://download.savannah.gnu.org/releases/lzip/lzlib/lzlib-1.5.tar.gz

Step 2. Install lzlib-1.5:

$ gunzip lzlib-1.5.tar.gz
$ tar -xvf lzlib-1.5.tar
$ cd lzlib-1.5
$ ./configure
$ make
$ make install

Step 3. Donwload Plzip 1.1

$ wget --no-check-certificate  http://download.savannah.gnu.org/releases/lzip/plzip/plzip-1.1.tar.gz

Step 4. Install Plzip

$ gunzip plzip-1.1.tar.gz
$ tar -xvf plzip-1.1.tar
$ cd plzip-1.1
$ ./configure
$ make
$ make install
