### ISSUE TITLE
removing additional contaminations

### ISSUE THREAD

**Issue by mictadlo** [oicr-ibc/cssscl#2]
Hi,
Does your tool work without any reference genome? If I would provide fasta files with chloroplast and mitochondrial genomes would your tool remove these genomes too?

Thank you in advance.

Michal

**Comment by iborozan** [comment]
The tool is designed to classify sequences against a database of known
reference sequences so it will not remove sequences as you describe. On the
other hand the tool could tell if your sequence originate from chloroplast
or methacondrial genomes.
Ivan
