### ISSUE TITLE
Cannot access any links 

### ISSUE THREAD

**Issue by twbattaglia** [oicr-ibc/cssscl#3]
It seems the URL's for the databases and setup files are not accessible anymore: 

```
wget --no-check-certificate https://collaborators.oicr.on.ca/vferretti/borozan_cssscl/data/taxon.tar.gz

> Resolving collaborators.oicr.on.ca (collaborators.oicr.on.ca)... failed: No address associated with hostname.
> wget: unable to resolve host address ‘collaborators.oicr.on.ca’
```

**Comment by iborozan** [comment]
These can now be downloaded from:

taxon:
https://drive.google.com/open?id=1okbaJkv6IgvWf8R1A97CX9lq10wV_INY

test/train:
https://drive.google.com/open?id=1glzuBJAqf5MPuO5_ivaFFLnZxpjnamFc

see the updated README file.

**Comment by twbattaglia** [comment]
Thanks! Is it also possible to have a working link to the Docker file?

https://collaborators.oicr.on.ca/vferretti/borozan_cssscl/code_2xx/ubuntucsss.tar.gz

**Comment by iborozan** [comment]
updated to a new location below: 
https://drive.google.com/open?id=1b08xOKHA_zz776JbqcYNAfYSQum3g_lm
